MAIN_WINDOW_SIZE = '500x700'
MAIN_WINDOW_TITLE = 'Виселица'
WIDTH, HEIGHT = False, False

GALLOWS_WINDOW_WIDTH = 300
GALLOWS_WINDOW_HEIGHT = 420
GALLOWS_WINDOW_PAD_Y = 20

GALLOWS_WINDOW_COLOR_MODE = 255
GALLOWS_WINDOW_BACKGROUND_COLOR = (240, 240, 240)

PENCIL_SIZE = 4
PENCIL_SPEED = 1.3

ERASER_SIZE = 50
ERASER_SPEED = 6
ERASER_SHAPE = 'circle'
ERASER_COLOR = (240, 240, 240)

FONT_WORD = ('Comic Sans MS', 18, 'bold')
WORD_LABEL_PAD_Y = 10

RESULT_WINDOW_REL_X = 0.5
RESULT_WINDOW_REL_Y = 0.6
FONT_RESULT = ('Comic Sans MS', 30, 'bold')

RIGHT_BUTTON_COLOR = 'chartreuse4'
VICTORY_LABEL_TEXT = 'ПОБЕДА'
VICTORY_LABEL_COLOR = 'green'

WRONG_BUTTON_COLOR = 'brown2'
DEFEAT_LABEL_TEXT = 'ПОРАЖЕНИЕ'
DEFEAT_LABEL_COLOR = 'brown'

LETTERS = 'ЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ'
BINDS = '''`qwertyuiop[]asdfghjkl;'zxcvbnm,.'''

KEYBOARD_FIRST_ROW_X = 20
KEYBOARD_FIRST_ROW_Y = 550
KEYBOARD_SECOND_ROW_X = 55
KEYBOARD_SECOND_ROW_Y = 585
KEYBOARD_THIRD_ROW_X = 90
KEYBOARD_THIRD_ROW_Y = 620
BUTTONS_DISTANCE_X = 35
BUTTON_SIZE = 32

FONT_BUTTON = ('Comic Sans MS', 14)
NONE_BUTTON_COLOR = 'yellow'
DEFAULT_BUTTON_COLOR = '#f0f0f0'
